In [ ]:
import numpy as np

In [ ]:
X = np.random.normal(loc=1, scale=10, size=(1000, 50))
print(X)

In [ ]:
m = np.mean(X, axis=0)
std = np.std(X, axis=0)
standard_X = ((X - m)/std)
print(standard_X)

In [12]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])
s = np.sum(Z, axis=1)
print(np.nonzero(s>10))

(array([1, 4, 5], dtype=int64),)


In [13]:
A = np.eye(3)
B = np.eye(3)
print(np.vstack((A,B)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
